---
abstract: 'Timing Statistics Class (Catalyst::Stats fork)'
author:
  - 'Carlos Fernando Avila Gratz <cafe@q1software.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-TimeStats
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Devel::TimeStats:
    file: lib/Devel/TimeStats.pm
    version: 0.03
requires:
  Moo: 1.002
  Term::ExtendedColor: 0.224
  Text::UnicodeTable::Simple: 0.08
  Time::HiRes: 1.9725
  Tree::Simple: 1.18
  Tree::Simple::Visitor::FindByUID: 0.02
  namespace::autoclean: 0.13
  perl: 5.008001
resources:
  bugtracker: https://github.com/cafe01/Devel-TimeStats/issues
  homepage: https://github.com/cafe01/Devel-TimeStats
  repository: git://github.com/cafe01/Devel-TimeStats.git
version: 0.03
x_contributors:
  - 'bayashi <bayashi@cpan.org>'
